#ifndef OGL_TEXTUREENUMS_HPP
#define OGL_TEXTUREENUMS_HPP

#include <glad/glad.h>

enum struct TextureMinFilter : GLint {
  NEAREST = GL_NEAREST,
  LINEAR = GL_LINEAR,
  NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
  LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
  NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
  LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR,
};

enum struct TextureMagFilter : GLint {
  NEAREST = GL_NEAREST,
  LINEAR = GL_LINEAR,
};

enum struct TextureWrap : GLint {
  CLAMP_TO_BORDER = GL_CLAMP_TO_BORDER,
  CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
  MIRRORED_REPEAT = GL_MIRRORED_REPEAT,
  MIRROR_CLAMP_TO_EDGE = GL_MIRROR_CLAMP_TO_EDGE,
  REPEAT = GL_REPEAT
};

enum struct CubeMapFace : GLenum {
  POSITIVE_X = GL_TEXTURE_CUBE_MAP_POSITIVE_X,
  NEGATIVE_X = GL_TEXTURE_CUBE_MAP_NEGATIVE_X,
  POSITIVE_Y = GL_TEXTURE_CUBE_MAP_POSITIVE_Y,
  NEGATIVE_Y = GL_TEXTURE_CUBE_MAP_NEGATIVE_Y,
  POSITIVE_Z = GL_TEXTURE_CUBE_MAP_POSITIVE_Z,
  NEGATIVE_Z = GL_TEXTURE_CUBE_MAP_NEGATIVE_Z,
};

enum struct CubeMapFaceIndex : GLint {
  POSITIVE_X = 0,
  NEGATIVE_X = 1,
  POSITIVE_Y = 2,
  NEGATIVE_Y = 3,
  POSITIVE_Z = 4,
  NEGATIVE_Z = 5,
};

#endif
