#ifndef OGL_ENUMS_HPP
#define OGL_ENUMS_HPP

#include <glad/glad.h>

enum struct BufferUsage : GLenum {
  STREAM_DRAW = GL_STREAM_DRAW,
  STREAM_READ = GL_STREAM_READ,
  STREAM_COPY = GL_STREAM_COPY,
  STATIC_DRAW = GL_STATIC_DRAW,
  STATIC_READ = GL_STATIC_READ,
  STATIC_COPY = GL_STATIC_COPY,
  DYNAMIC_DRAW = GL_DYNAMIC_DRAW,
  DYNAMIC_READ = GL_DYNAMIC_READ,
  DYNAMIC_COPY = GL_DYNAMIC_COPY,
};

enum struct StorageFlag : GLbitfield {
  DYNAMIC_STORAGE = GL_DYNAMIC_STORAGE_BIT,
  MAP_READ = GL_MAP_READ_BIT,
  MAP_WRITE = GL_MAP_WRITE_BIT,
  MAP_PERSISTENT = GL_MAP_PERSISTENT_BIT,
  MAP_COHERENT = GL_MAP_COHERENT_BIT,
  CLIENT_STORAGE = GL_CLIENT_STORAGE_BIT,
};

enum struct MappingFlag : GLbitfield {
  MAP_PERSISTENT = GL_MAP_PERSISTENT_BIT,
  MAP_COHERENT = GL_MAP_COHERENT_BIT,
  MAP_INVALIDATE_RANGE = GL_MAP_INVALIDATE_RANGE_BIT,
  MAP_INVALIDATE_BUFFER = GL_MAP_INVALIDATE_BUFFER_BIT,
  MAP_FLUSH_EXPLICIT = GL_MAP_FLUSH_EXPLICIT_BIT,
  MAP_UNSYNCHRONIZED = GL_MAP_UNSYNCHRONIZED_BIT,
};

enum struct IndexFormat : GLenum {
  // all index data types supported by OpenGL
  // ========================================
  UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
  UNSIGNED_SHORT = GL_UNSIGNED_SHORT,
  UNSIGNED_INT = GL_UNSIGNED_INT,
};

#endif
